services:
  hyperbeam:
    image: ghcr.io/ar-io/hyperbeam:latest
    restart: unless-stopped
    command: "foreground"
    ports:
      - ${HB_PORT:-10000}:10000
    volumes:
      - ${HB_CACHE:-./data/hyperbeam/cache-mainnet}:/opt/_build/genesis_wasm/rel/hb/cache-mainnet
    networks:
      - ar-io-network

networks:
  ar-io-network:
    external: true
